name: "Check SemVer"
description: "Check semver and compare to PR target. Sync main branch tag with package.json version."
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "package"
  color: "blue"
